### PR TITLE
[bugfix] Use proper atomic units for staking balances

### PR DESCRIPTION
**Pull request by deangalvin-cb**
### What changed? Why?
This updates the internal parsing of balance objects from whole units to atomic units to match other balance usage.

#### Qualified Impact
This impacts the way balances are parsed internally and should not break any client usage.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by marchsu — COMMENTED** [review]
`toString()` might need to change as well, perhaps removes the `ETH` as it is showing the rawNum

**Review by ProfMoo — APPROVED** [review]
LGTM!

**Comment by marchsu** [comment]
got this when testing locally
```
StakingBalance { date: '2024-08-14T00:00:00.000Z' address: '0x80000001677f23a227dfed6f61b132d114be83b8ad0aa5f3c5d1d77e6ee0bf5f73b0af750cc34e8f2dae73c21dc36f4a' bondedStake: '3.2e-17 ETH' unbondedBalance: '5.566622738e-18 ETH' participantType: 'VALIDATOR' }
```

**Review by marchsu — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for marchsu @ 2024-08-27 19:00:37 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by marchsu — APPROVED** [review]

**Review by marchsu — APPROVED** [review]

**Review by alex-stone — APPROVED** [review]

**Pull request merged**
