### PR TITLE
Updating CHANGELOG.md

### PR DESCRIPTION
**Pull request by erdimaden**
### What changed? Why?
Updating CHANGELOG.md

### CODE REVIEW

**Review by jazz-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-nodejs/issues/90) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-nodejs/issues/90) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-nodejs/issues/90) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-nodejs/issues/90) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-nodejs/issues/90) to review and +1

**Pull request merged**
